### ISSUE TITLE
Parser doesn't seem to work

### ISSUE THREAD

**Issue by 0xjbb** [plyara/plyara#128]
I'm getting a bunch of errors by using this project, anybody have any ideas on why this is?

Python 3.12

```
(.venv) PS C:\Users\admin\PycharmProjects\project1> python .\main.py -f C:\Temp\Example.yar -d . --testing                
ERROR: No token list is defined
ERROR: No rules of the form t_rulename are defined
ERROR: No rules defined for state 'INITIAL'
Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\project1\main.py", line 36, in <module>
    main()
  File "C:\Users\admin\PycharmProjects\project1\main.py", line 28, in main
    yara = plyara.Parser()
           ^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\project1\.venv\Lib\site-packages\plyara\core.py", line 129, in __init__
    self.lexer = lex.lex(module=self, debug=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\project1\.venv\Lib\site-packages\ply\lex.py", line 909, in lex
    raise SyntaxError("Can't build lexer")
SyntaxError: Can't build lexer
```

**Comment by utkonos** [comment]
It looks like you're using plyara as a python module in your own code. Please share your code so I can see all of how you're instantiating and calling plyara. Also, please share the yara file that you're using.

**Comment by utkonos** [comment]
Try again with the latest version of plyara. If this bug is still happening, please reopen this issue and provide both the Python code you're using as well as the YARA rule/s that you're parsing.
