### ISSUE TITLE
Version 2.2.2 has issues

### ISSUE THREAD

**Issue by Neo23x0** [plyara/plyara#143]
```
[ERROR] Error parsing YARA rule file './thor-hacktools.yar'
Traceback (most recent call last):
  File "/builds/internal-researcher/signature-sources/mjolnir/main/core.py", line 398, in readFiles
    rules_list = p.parse_string(file_data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/internal-researcher/signature-sources/.venv/lib/python3.11/site-packages/plyara/core.py", line 361, in parse_string
    self.parser.parse(input_string, lexer=self.lexer)
  File "/builds/internal-researcher/signature-sources/.venv/lib/python3.11/site-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/internal-researcher/signature-sources/.venv/lib/python3.11/site-packages/ply/yacc.py", line 1201, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/internal-researcher/signature-sources/.venv/lib/python3.11/site-packages/ply/yacc.py", line 192, in call_errorfunc
    r = errorfunc(token)
        ^^^^^^^^^^^^^^^^
  File "/builds/internal-researcher/signature-sources/.venv/lib/python3.11/site-packages/plyara/core.py", line 1242, in p_error
    raise ParseTypeError(message, p.lineno, p.lexpos)
plyara.exceptions.ParseTypeError: Unknown text -0xff for token of type HEXNUM on line 49290
```

It seems that it has issues with the `xor` key expressions, e.g.
```
$xbug = "CatalogChangeListener-##-##" xor(0x01-0xff)
```
which it didn't have before

**Comment by utkonos** [comment]
@Neo23x0 This is downstream from the fix to parsing negative (`NUM` | `HEXNUM`) in `condition`. I'll get this fixed today and include a unit test so it never comes back.

Thanks for the report!

**Comment by utkonos** [comment]
I have identified exectly where this bug is located. This bug was introduced by the bug fix for negative numbers in conditions. The fix requires me to untangle some contributed code:

https://github.com/plyara/plyara/blob/5944db3b66770b9824118b038040b3bdabecfeaf/src/plyara/core.py#L1044-L1072

I will get this fixed asap.

**Comment by Neo23x0** [comment]
okay, great

**Comment by Derekt2** [comment]
Hi @utkonos, wondering if you had a fix or workaround for this issue in the meantime? We ran into this while parsing our rules and is blocking us from upgrading to 2.2.2

Happy New Year!

**Comment by utkonos** [comment]
@Derekt2 Working on it.

**Comment by utkonos** [comment]
@Derekt2 @Neo23x0 @cccs-rs This regression is fixed.
