### ISSUE TITLE
Error parsing Regex strings in newest v1.2.6

### ISSUE THREAD

**Issue by Neo23x0** [plyara/plyara#23]
Up to now I was working with version 1.2.5, which worked fine. 
The newest master produces errors with many of my regex YARA strings. 

```
Traceback (most recent call last):
  File "mjolnir.py", line 166, in readFiles
    rulesList = p.parse_string(fileData)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plyara-1.2.6-py3.6.egg/plyara.py", line 210, in parse_string
    yacc.parse(input_string)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ply-3.11-py3.6.egg/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ply-3.11-py3.6.egg/ply/yacc.py", line 1201, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ply-3.11-py3.6.egg/ply/yacc.py", line 192, in call_errorfunc
    r = errorfunc(token)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plyara-1.2.6-py3.6.egg/plyara.py", line 1087, in p_error
    raise TypeError(u'Unknown text {} for token of type {} on line {}'.format(p.value, p.type, p.lineno))
TypeError: Unknown text [ for token of type LBRACK on line 78
```

The parser fails on regular expression strings like this
```
      $d = /\x00https?:\/\/[^\x00]{4,500}\x00\x00\x00/
```

I guess that this commit introduced the errors:
https://github.com/plyara/plyara/commit/0c4e814e139cac27c9cf0f7945b534c99c960c47

**Comment by Taskr** [comment]
Thanks for submitting the issue @Neo23x0. The logic in t_REXSTRING_end appears to be prematurely terminating the string. Working on a fix currently.

**Comment by rshipp** [comment]
Pushed to PyPI as v1.2.7. 

@Neo23x0 can you confirm this and #24 are fixed with v1.2.7?

**Comment by Neo23x0** [comment]
Persist - this time for curly brackets
```
Traceback (most recent call last):
  File "mjolnir.py", line 166, in readFiles
    rulesList = p.parse_string(fileData)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plyara-1.2.7-py3.6.egg/plyara.py", line 210, in parse_string
    yacc.parse(input_string)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ply-3.11-py3.6.egg/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ply-3.11-py3.6.egg/ply/yacc.py", line 1201, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ply-3.11-py3.6.egg/ply/yacc.py", line 192, in call_errorfunc
    r = errorfunc(token)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plyara-1.2.7-py3.6.egg/plyara.py", line 1089, in p_error
    raise TypeError(u'Unknown text {} for token of type {} on line {}'.format(p.value, p.type, p.lineno))
TypeError: Unknown text { for token of type LBRACE on line 895
```

**Comment by Neo23x0** [comment]
Cool - you version of `plyara` is on PyPI? I thought it was still https://github.com/8u1a/plyara
Ah, you got access in July this year! Great

**Comment by Neo23x0** [comment]
I guess i have the perfect test set - 9762 YARA hand crafted rules, written for YARA versions since v1.7, external variables and all kind of conditions. 

![screenshot 2018-10-16 at 15 33 48](https://user-images.githubusercontent.com/2851492/47020105-e985fe00-d158-11e8-9b42-7913b3bf7680.png)

**Comment by Taskr** [comment]
Awesome :) That is a very impressive test set! Hopefully this will fix the issue.

**Comment by rshipp** [comment]
Pushed #26 as v1.2.8.

Thanks for the help Florian, always nice to have more test cases. :)

**Comment by Neo23x0** [comment]
Fixed in https://github.com/plyara/plyara/commit/0e1847dafee6a6108711e93e9e15ffec48c3eedb
