### ISSUE TITLE
plyara does not recognise base64 keyword

### ISSUE THREAD

**Issue by tlansec** [plyara/plyara#94]
Hello,

In YARA >= 4.0 new modifiers were introduced to support matching base64 encoded strings. 

Here are some example rules that YARA will accept which currently causes errors when using Plyara:

```
rule example_base64
{
strings:
	$foo = "string" base64

condition:
	$foo
}

rule example_base64wide
{
strings:
	$foo = "string" base64wide 
condition:	
	$foo
}

rule example_base64_customalpha 
{
strings:
	$foo = "string" base64("!@#$%^&*(){}[].,|ABCDEFGHIJ\x09LMNOPQRSTUVWXYZabcdefghijklmnopqrstu")
condition:
	$foo
}
```

Example code to illustrate current error shown:

```
import plyara

with open("foo.txt") as infile:
    text = infile.read()

plyara_obj = plyara.Plyara()
plyara_obj.parse_string(text)
```

Throws:

```
λ python tmp.py
Traceback (most recent call last):
  File "tmp.py", line 7, in <module>
    plyara_obj.parse_string(text)
  File "C:\Users\tomla\AppData\Local\Programs\Python\Python36\lib\site-packages\plyara\core.py", line 244, in parse_string
    self.parser.parse(input_string, lexer=self.lexer)
  File "C:\Users\tomla\AppData\Local\Programs\Python\Python36\lib\site-packages\ply\yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "C:\Users\tomla\AppData\Local\Programs\Python\Python36\lib\site-packages\ply\yacc.py", line 1201, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "C:\Users\tomla\AppData\Local\Programs\Python\Python36\lib\site-packages\ply\yacc.py", line 192, in call_errorfunc
    r = errorfunc(token)
  File "C:\Users\tomla\AppData\Local\Programs\Python\Python36\lib\site-packages\plyara\core.py", line 975, in p_error
    raise ParseTypeError(message, p.lineno, p.lexpos)
plyara.exceptions.ParseTypeError: Unknown text base64 for token of type ID on line 4
```

Cheers,
Tom

**Comment by tlansec** [comment]
Ah - it looks like this will be resolved by this PR:

https://github.com/plyara/plyara/pull/92

Please link and close if appropriate.

Cheers,
Tom

**Comment by utkonos** [comment]
@tlansec No need to close. I will link this issue and it will be closed when I merge that PR. I have set aside time this weekend to get caught up with the PRs, issues, and the update to SLY. Please stay tuned!
